name = "Basic Demo"
id = "basicdemo"
version = "0.1a"
ruleset = "camp.engine.rules.basicdemo"


[name_overrides]
class = "Class"
spell = "Spell"
skill = "Skill"
feat = "Feat"
sp = "Skill Points"
strike = "Strike Damage"
spells = "Spells Known"
powers = "Powers Known"
backstab = "Backstab Damage"
hp = "HP"
armor = "Armor"
