type = "class"
name = "Thief"
description = """
The thief is more technical than the fighter, but significantly
more pragmatic and down-to-earth than the mage. Matching their
prgamatism, TOML is their secret tongue.
"""

grants = [
    "light-armor",
    "simple-weapon",
    "legerdemain",
]

levels = [
    {backstab = 2, powers = 1, hp = 1, sp = 1},
    {strike = 1, backstab = 2, hp = 1, sp = 2},
    {backstab = 2, hp = 1, powers = 1, sp = 1},
    {backstab = 2, hp = 1, sp = 1},
    {backstab = 2, strike = 1, powers = 1, hp = 1, sp = 2}
]
